name: Generate Resource Configuration

on:
  workflow_dispatch:
    inputs:
      resource_type:
        description: "Type of resource to configure (kinesis_firehose, s3_bucket, sqs)"
        required: true
        default: "kinesis_firehose"
        # Users will enter a comma-separated list of variables they want to set
      json_file_name:
        description: "Name of the JSON file to be created (without extension)"
        required: true
        default: "resource_config"
      kinesis_firehose_inputs:
        description: "Comma-separated values for kinesis_firehose (stream_name,s3_bucket_arn,s3_prefix,buffer_size,buffer_interval,role_arn)"
        required: false
        default: ""
      s3_bucket_inputs:
        description: "Comma-separated values for s3_bucket (bucket_name,acl,versioning)"
        required: false
        default: ""
      sqs_inputs:
        description: "Comma-separated values for sqs (queue_name,delay_seconds,maximum_message_size)"
        required: false
        default: ""

jobs:
  generate_configuration:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate configuration file
        run: |
          RESOURCE_TYPE="${{ github.event.inputs.resource_type }}"
          JSON_FILE_NAME="${{ github.event.inputs.json_file_name }}"

          # Function to parse comma-separated values into JSON format
          parse_csv_to_json() {
            IFS=',' read -r -a values <<< "$1"
            case "$RESOURCE_TYPE" in
              "kinesis_firehose")
                echo "{
                  \"stream_name\": \"${values[0]}\",
                  \"s3_bucket_arn\": \"${values[1]}\",
                  \"s3_prefix\": \"${values[2]}\",
                  \"buffer_size\": ${values[3]},
                  \"buffer_interval\": ${values[4]},
                  \"role_arn\": \"${values[5]}\"
                }"
                ;;
              "s3_bucket")
                echo "{
                  \"bucket_name\": \"${values[0]}\",
                  \"acl\": \"${values[1]}\",
                  \"versioning\": ${values[2]}
                }"
                ;;
              "sqs")
                echo "{
                  \"queue_name\": \"${values[0]}\",
                  \"delay_seconds\": ${values[1]},
                  \"maximum_message_size\": ${values[2]}
                }"
                ;;
              *)
                echo "Invalid resource type"
                exit 1
                ;;
            esac
          }

          # Generate the JSON configuration file based on the resource type
          case "$RESOURCE_TYPE" in
            "kinesis_firehose")
              CONFIG_JSON=$(parse_csv_to_json "${{ github.event.inputs.kinesis_firehose_inputs }}")
              ;;
            "s3_bucket")
              CONFIG_JSON=$(parse_csv_to_json "${{ github.event.inputs.s3_bucket_inputs }}")
              ;;
            "sqs")
              CONFIG_JSON=$(parse_csv_to_json "${{ github.event.inputs.sqs_inputs }}")
              ;;
            *)
              echo "Invalid resource type: $RESOURCE_TYPE"
              exit 1
              ;;
          esac

          # Write the JSON to the file
          echo "$CONFIG_JSON" > ./$JSON_FILE_NAME.json

      - name: Commit and Push configuration file
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          git config --global user.name 'fvder'
          git config --global user.email 'joseph.duduyemi09@gmail.com'
          git checkout master
          git pull https://${{ secrets.ACTIONS_PAT }}@github.com/fvder/practice-test master
          git add ./${{ github.event.inputs.json_file_name }}.json
          git commit -m "Add generated ${{ github.event.inputs.resource_type }} configuration - $(date)"
          git push https://${{ secrets.ACTIONS_PAT }}@github.com/fvder/practice-test HEAD:refs/heads/master
