name: Generate kinesis_firehose.json

on:
  workflow_dispatch:
    inputs:
      commit_message:
        description: "Commit message"
        required: true
        default: "Add generated kinesis_firehose.json"
      deploy:
        description: "Boolean to deploy resources"
        required: true
        default: true
        type: boolean
      stream_name:
        description: "Name of the firehose stream"
        required: true
        default: ""
      s3_bucket_arn:
        description: "ARN of the S3 bucket"
        required: true
        default: ""
      s3_prefix:
        description: "S3 prefix"
        required: true
        default: ""
      buffer_size:
        description: "Buffer size in MBs"
        required: true
        default: 5
        type: number
      buffer_interval:
        description: "Buffer interval in seconds"
        required: true
        default: 300
        type: number
      role_arn:
        description: "IAM role ARN"
        required: true
        default: ""
      kms_key_arn:
        description: "KMS key ARN for S3 bucket encryption"
        required: true
        default: ""
      sse_kms_key_type:
        description: "SSE KMS key type"
        required: true
        default: "AWS_OWNED_CMK"

jobs:
  generate_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Generate kinesis_firehose.json
        run: |
          echo '{
            "deploy": ${{
              github.event.inputs.deploy
            }},
            "stream_name": "${{
              github.event.inputs.stream_name
            }}",
            "s3_bucket_arn": "${{
              github.event.inputs.s3_bucket_arn
            }}",
            "s3_prefix": "${{
              github.event.inputs.s3_prefix
            }}",
            "buffer_size": ${{
              github.event.inputs.buffer_size
            }},
            "buffer_interval": ${{
              github.event.inputs.buffer_interval
            }},
            "role_arn": "${{
              github.event.inputs.role_arn
            }}",
            "kms_key_arn": "${{
              github.event.inputs.kms_key_arn
            }}",
            "sse_kms_key_type": "${{
              github.event.inputs.sse_kms_key_type
            }}"
          }' > ./kinesis_firehose.json

      - name: Commit and Push kinesis_firehose.json
        env:
          ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
        run: |
          git config --global user.name 'fvder'
          git config --global user.email 'joseph.duduyemi09@gmail.com'
          git checkout master
          git pull https://${{ secrets.ACTIONS_PAT }}@github.com/fvder/practice-test.git master
          git add ./kinesis_firehose.json
          git commit -m "${{ github.event.inputs.commit_message }} - $(date)"
          git push https://${{ secrets.ACTIONS_PAT }}@github.com/fvder/practice-test.git