name: EDP-devops-s3-upload-test-file-poc

on: 
  workflow_dispatch:
    inputs:
      bucket_name:
        description: 'S3 Bucket Name'
        required: true
      region_id:
        description: 'AWS Region ID'
        required: true

jobs:
  aws-operations:
    runs-on: ubuntu-latest
    env:
      BUCKET_NAME: ${{ github.event.inputs.bucket_name }}
      REGION_ID: ${{ github.event.inputs.region_id }}
      KMS_KEY: ${{ secrets.KMS_KEY }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ github.event.inputs.region_id }}

    - name: List S3 Bucket
      run: aws s3 ls s3://${{ env.BUCKET_NAME }}/ --region ${{ env.REGION_ID }} --cli-connect-timeout 10

    - name: Upload file to AWS S3
      run: |
        echo "test" > /tmp/test.txt
        aws s3 cp /tmp/test.txt s3://${{ env.BUCKET_NAME }}/test22.txt --region ${{ env.REGION_ID }} --sse aws:kms --sse-kms-key-id alias/${{ env.KMS_KEY }} --cli-connect-timeout 10

    - name: Wait to check
      run: |
        echo "Waiting 5 minutes to check that file is in the S3 bucket"
        sleep 300

    - name: Delete AWS S3 file
      run: aws s3 rm s3://${{ env.BUCKET_NAME }}/test22.txt --region ${{ env.REGION_ID }}